# Generated by Django 5.1.1 on 2024-11-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcat_name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='finance.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom', models.CharField(blank=True, max_length=255, null=True)),
                ('t_date', models.DateField()),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_category', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to='finance.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.usercategory'),
        ),
    ]
