# Generated by Django 5.1.1 on 2024-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_subcategory_transaction_usercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_name',
            field=models.CharField(default='Default Category', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subcategory_name',
            field=models.CharField(default='Default SubCategory', max_length=150),
        ),
    ]
