# Generated by Django 5.1.1 on 2024-12-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_customuser_deleted_at_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
    ]
