name: Sync with GitLab

on:
  push:
    branches:
      - master  # Replace with your default branch if different

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Sandy2k3"
          git config --global user.email "sandeshgc2003@gmail.com"

      - name: Add GitLab Remote
        run: git remote add gitlab https://gitlab.com/Sandy2k3/Finance-Tracker.git

      - name: Push to GitLab
        run: |
          git push -u gitlab master --force
